version: '2'
services:  
  scp-server:
    network_mode: host
    restart: always
    build: ./scp-server
    privileged: false
    labels:
      io.balena.features.dbus: 1
    volumes:
      - serverfiles:/serverfiles
      - servercache:/servercache
    ports:
      - "22:22/udp"
      - "22:22/tcp"
  ddclient:
    network_mode: host
    restart: on-failure
    build: ./ddclient
    privileged: false
    labels:
      io.balena.features.dbus: 1
    volumes:
      - serverfiles:/serverfiles
      - servercache:/servercache      
volumes:
  serverfiles:
  servercache:
