version: '2'
services:  
  scp-server:
    network_mode: host
    restart: always
    build: ./scp-server
    privileged: false
    labels:
      io.balena.features.dbus: 1
    volumes:
      - serverfiles:/serverfiles
      - servercache:/servercache
    ports:
      - "22:22/udp"
      - "22:22/tcp"  
  balena-rcon:
    network_mode: host
    restart: always
    build: ./balena-rcon
    privileged: true
    ports:
      - "25575:25575/udp"
      - "25575:25575/tcp"
  dynu-dns:
      network_mode: host
      restart: always
      build: ./dynu-dns
      privileged: false
      labels:
        io.balena.features.dbus: 1
      volumes:
        - serverfiles:/serverfiles      
volumes:
  serverfiles:
  servercache:
